language: cpp
compiler:
  - clang++
addons:
  apt:
    sources:
      - boost-latest
    packages:
      - gcc-4.8
      - g++-4.8
      - libboost1.55-all-dev
      - cmake
script: mkdir build && cd build && cmake .. && make VERBOSE=1 && cd ..
